# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test build-deploy

on:
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: charybdis
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - uses: a11ywatch/github-action@v2.1.10
      with:
        WEBSITE_URL: "https://charybdis-agh5deebangwbrey.ukwest-01.azurewebsites.net/"
        SITE_WIDE: true
        SUBDOMAINS: false
        TLD: false
        SITEMAP: true
        FAIL_ERRORS_COUNT: 15
        LIST: true
        FIX: false
        UPGRADE: false
        UPLOAD: true
      env:
        DEFAULT_RUNNERS: htmlcs,axe
        PAGEMIND_IGNORE_WARNINGS: true
        AI_DISABLED: false